import path from 'node:path';
import { promises as fs } from 'node:fs';

import type { SponsorLane } from './sponsor-lanes.js';

export const sponsorLaneOrder = ['request', 'output', 'registry', 'credits'] as SponsorLane[];

export interface LocalRuntimeIsolationArtifacts {
  envPath: string;
  launchPath: string;
  retainedLanes: SponsorLane[];
  disabledLanes: SponsorLane[];
  routeStrategy: 'membership-first';
}

export function parseSponsorLaneList(value: unknown, fallback: SponsorLane[] = []) {
  const raw = Array.isArray(value)
    ? value
    : typeof value === 'string'
      ? value
          .split(',')
          .map((entry) => entry.trim())
          .filter(Boolean)
      : fallback;
  const unique = new Set<SponsorLane>();
  raw.forEach((entry) => {
    if (sponsorLaneOrder.includes(entry as SponsorLane)) {
      unique.add(entry as SponsorLane);
    }
  });
  return sponsorLaneOrder.filter((lane) => unique.has(lane));
}

export async function writeLocalRuntimeIsolationFiles(options: {
  repoRoot: string;
  operatorsDir: string;
  localOperatorId: string;
  retainedLanes: SponsorLane[];
  coordinatorEnvPath?: string | null;
}) {
  const retainedLanes = parseSponsorLaneList(options.retainedLanes, sponsorLaneOrder);
  const disabledLanes = sponsorLaneOrder.filter((lane) => !retainedLanes.includes(lane));
  const envPath = path.join(options.operatorsDir, `${options.localOperatorId}.local-isolation.env`);
  const launchPath = path.join(options.operatorsDir, `${options.localOperatorId}.local-isolation.launch.sh`);
  const envLines = [
    '# Generated by Zeko AI Runtime local-runtime isolation tooling.',
    '# Source this file alongside your normal coordinator env before starting the local coordinator.',
    'OPENGRADIENT_ROUTE_STRATEGY=membership-first',
    `OPENGRADIENT_DISABLED_SPONSOR_LANES=${disabledLanes.join(',')}`,
    `OPENGRADIENT_OPERATOR_ID=${options.localOperatorId}`
  ];
  await fs.mkdir(options.operatorsDir, { recursive: true });
  await fs.writeFile(envPath, `${envLines.join('\n')}\n`, 'utf8');

  const launchLines = ['#!/bin/zsh', 'set -euo pipefail', `cd ${JSON.stringify(options.repoRoot)}`, 'set -a'];
  if (typeof options.coordinatorEnvPath === 'string' && options.coordinatorEnvPath.trim().length > 0) {
    launchLines.push(
      `if [[ -f ${JSON.stringify(options.coordinatorEnvPath)} ]]; then`,
      `  . ${JSON.stringify(options.coordinatorEnvPath)}`,
      'fi'
    );
  }
  launchLines.push(`. ${JSON.stringify(envPath)}`, 'set +a', 'exec npm start');
  await fs.writeFile(launchPath, `${launchLines.join('\n')}\n`, 'utf8');
  await fs.chmod(launchPath, 0o700);

  const artifacts: LocalRuntimeIsolationArtifacts = {
    envPath,
    launchPath,
    retainedLanes,
    disabledLanes,
    routeStrategy: 'membership-first'
  };
  return artifacts;
}
